import { Poppins } from 'next/font/google';
import "./globals.css";
import '../utils/fontawesome';
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.min.css';


const poppins = Poppins({
  subsets: ['latin'], // choose subsets you need
  weight: ['400', '500', '600', '700'], // choose font weights you need
  variable: '--font-poppins', // optional for CSS variable
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
